#
# This site was originally deployed by Netlify to https://wom.christmind.info. This has changed
# so that it is incorporated into the Netlify site cmi-www and is accessed at
# https://www.christmind.info/t/wom.
#
# This config file is used update the cmi-wom Netlify site with a page that imforms the user
# that the site has moved and to include a _redirects file that will forward references to 
# https://wom.christmind.info to the appropriate destination.
#
# To develop this site
#
# 1. npm run deploy:netlify
# 2. Edit moved.md, _redirects and any other files
# 3. Test locally at localhost:9912
# 4. Use the command line from the project root to deploy to Netlify
#     $ netlify deploy --prod
#
# The switch from https://wom.christmind.info to https://www.christmind.info/t/acol happened
# on March 19, 2019. Maintaining the old Netlify site, cmi-wom, is needed only for a short 
# time.
#
# CMI
sourceId: 10
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'Way of Mastery'
tagline:      'Now, we begin...'
description:  'A pathway of awakening from Jeshua through Jon Marc Hammer (Jayem)'
url:          'https://wom.christmind.info'
baseurl:      ''
keywords:     "Christ Mind, Way of Mastery, Jeshua, Jayem, Way of the Heart, Way of Transformation, Way of Knowing"
port:         9910

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
src-url:      'https://wom.christmind.info'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

include: [ _redirects ]

exclude: [
  deploy,
  LICENSE,
  README.md,
  Gemfile,
  Gemfile.lock,
  package.json,
  package-lock.json,
  node_modules,
  webpack.config.js,
  src,
  project,
  _acq,
  _early,
  _tjl,
  _woh,
  _wot,
  _wok,
  _wos
]

