# CMI
destination: "../cmi-www/t/wom"

sourceId: 10
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'The Way of Mastery'
tagline:      'Now, we begin...'
description:  'A pathway of awakening from Jeshua through Jon Marc Hammer (Jayem)'
url:          'https://www.christmind.info/t/wom'
baseurl:      ''
keywords:     "Christ Mind, Way of Mastery, Jeshua, Jayem, Way of the Heart, Way of Transformation, Way of Knowing"
port:         9910

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
semantic:     fui292
#semantic:     fui286
#semantic:     sui231
#semantic:     sui241
src-url:      'https://www.christmind.info/t/wom'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

# Collections for transcripts
collections:
  video:
    output: true
  notes:
    output: true
  acq:
    output: true
    title: Get Acquainted
  woh:
    output: true
    title: Way of the Heart
  wot:
    output: true
    title: Way of Transformation
  wok:
    output: true
    title: Way of Knowing
  wos:
    output: true
    title: Way of the Servant
  tjl:
    output: true
    title: The Jeshua Letters
  early:
    output: true
    title: The Early Years
  questions:
    output: true
    title: Questions
  topics:
    output: true
    title: Topics and Index
  reveal:
    output: true
    title: Presentations
  rick:
    output: true
    title: Rick's Notes

defaults:
  - scope:
      path: ""
      type: video
    values:
      layout: transcript
  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/t/wom/public/img/wom/acq-big.jpg"
      image-width: 612
      image-height: 792
      bid: "acq"
      audio: false
      pnumToggle: false
  - scope:
      path: ""
      type: woh
    values:
      layout: transcript
      book: "Way of the Heart"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/woh-big.jpg"
      image-width: 612
      image-height: 928
      bid: "WOH"
  - scope:
      path: ""
      type: wot
    values:
      layout: transcript
      book: "Way of Transformation"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/wot-big.jpg"
      image-width: 612
      image-height: 924
      "bid": "WOT"
  - scope:
      path: ""
      type: wok
    values:
      layout: transcript
      book: "Way of Knowing"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/wok-big.jpg"
      image-width: 612
      image-height: 926
      bid: "WOK"
  - scope:
      path: ""
      type: wos
    values:
      layout: transcript
      book: "Way of the Servant"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/wosN-big.jpg"
      line2: "/t/wom/public/img/wom/line2.jpg"
      line4: "/t/wom/public/img/wom/line4.jpg"
      image-width: 612
      image-height: 926
      bid: "WOS"
  - scope:
      path: ""
      type: tjl
    values:
      layout: transcript
      book: "The Jeshua Letters"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/tjlN-big.jpg"
      line2: "/t/wom/public/img/wom/line2.jpg"
      line4: "/t/wom/public/img/wom/line4.jpg"
      image-width: 612
      image-height: 938
      bid: "TJL"
      audio: false
  - scope:
      path: ""
      type: early
    values:
      layout: transcript
      book: "The Early Years"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/earlyN-early.jpg"
      image-width: 612
      image-height: 926
      bid: "Early"
  - scope:
      path: ""
      type: rick
    values:
      layout: transcript
      book: "Rick's Notes"
      publisher: "CMI"
      image: "/t/wom/public/img/wom/earlyN-early.jpg"
      image-width: 612
      image-height: 926
      bid: "Rick"
  - scope:
      path: ""
      type: topics
    values:
      layout: topic
      book: "Topics"
      publisher: "CMI"
      image: "/t/wom/public/img/wom/earlyN-big.jpg"
      image-width: 612
      image-height: 926
      bid: "Topics"
  - scope:
      path: ""
      type: reveal
    values:
      layout: reveal
      book: "Reveal"
      publisher: "CMI"
      image: "/t/wom/public/img/wom/earlyN-big.jpg"
      image-width: 612
      image-height: 926
      bid: "Reveal"

exclude: [
  moved.html, deploy, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

