# CMI
destination: "../cmi-www/t/wom"

sourceId: 10
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'Way of Mastery'
tagline:      'Now, we begin...'
description:  'A pathway of awakening from Jeshua through Jon Marc Hammer (Jayem)'
url:          'https://www.christmind.info/t/wom'
baseurl:      ''
keywords:     "Christ Mind, Way of Mastery, Jeshua, Jayem, Way of the Heart, Way of Transformation, Way of Knowing"
port:         9910

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
src-url:      'https://www.christmind.info/t/wom'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-sitemap

#  - jekyll-feed

# Collections for transcripts
collections:
  acq:
    output: true
    title: Get Acquainted
  woh:
    output: true
    title: Way of the Heart
  wot:
    output: true
    title: Way of Transformation
  wok:
    output: true
    title: Way of Knowing
  wos:
    output: true
    title: Way of the Servant
  tjl:
    output: true
    title: The Jeshua Letters
  early:
    output: true
    title: The Early Years
  questions:
    output: true
    title: Questions

defaults:
  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/t/wom/public/img/wom/acq-big.jpg"
      image-width: 612
      image-height: 792
      bid: "acq"
      audio: false
  - scope:
      path: ""
      type: woh
    values:
      layout: transcript
      book: "Way of the Heart"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/woh-big.jpg"
      image-width: 612
      image-height: 792
      bid: "WOH"
  - scope:
      path: ""
      type: wot
    values:
      layout: transcript
      book: "Way of Transformation"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/wot-big.jpg"
      image-width: 612
      image-height: 792
      "bid": "WOT"
  - scope:
      path: ""
      type: wok
    values:
      layout: transcript
      book: "Way of Knowing"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/wok-big.jpg"
      image-width: 612
      image-height: 792
      bid: "WOK"
  - scope:
      path: ""
      type: wos
    values:
      layout: transcript
      book: "Way of the Servant"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/wos-big.jpg"
      line2: "/t/wom/public/img/wom/line2.jpg"
      line4: "/t/wom/public/img/wom/line4.jpg"
      image-width: 612
      image-height: 792
      bid: "WOS"
      audio: false
  - scope:
      path: ""
      type: tjl
    values:
      layout: transcript
      book: "The Jeshua Letters"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/tjl-big.jpg"
      line2: "/t/wom/public/img/wom/line2.jpg"
      line4: "/t/wom/public/img/wom/line4.jpg"
      image-width: 612
      image-height: 792
      bid: "TJL"
      audio: false
  - scope:
      path: ""
      type: early
    values:
      layout: transcript
      book: "The Early Years"
      publisher: "Way of Mastery"
      image: "/t/wom/public/img/wom/early.jpg"
      image-width: 250
      image-height: 324
      bid: "Early"

exclude: [
  moved.html, deploy, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

